interface OrganizationAdminRow {
  id: string;
  name: string;
  public_key: string | null;
  private_key: string | null;
}

export function organizationAdminToResponse(org: OrganizationAdminRow) {
  return {
    id: org.id,
    name: org.name,
    businessName: null,
    businessAddress1: null,
    businessAddress2: null,
    businessAddress3: null,
    businessCountry: null,
    businessTaxNumber: null,
    billingEmail: null,
    plan: {
      type: 0,
      productTier: 0,
      name: "Free",
      isAnnual: false,
      nameLocalizationKey: null,
      descriptionLocalizationKey: null,
      canBeUsedByBusiness: true,
      trialPeriodDays: null,
      hasSelfHost: true,
      hasPolicies: true,
      hasGroups: false,
      hasDirectory: false,
      hasEvents: false,
      hasTotp: true,
      has2fa: true,
      hasApi: true,
      hasSso: false,
      hasOrganizationDomains: false,
      hasResetPassword: false,
      usersGetPremium: true,
      hasMyItems: false,
      hasInviteLinks: false,
      upgradeSortOrder: 0,
      displaySortOrder: 0,
      legacyYear: null,
      disabled: false,
      secretsManager: null,
      passwordManager: null,
      object: "plan",
    },
    secretsManagerPlan: null,
    planType: 0,
    seats: 20,
    maxAutoscaleSeats: null,
    maxCollections: null,
    maxStorageGb: 32767,
    usePolicies: true,
    useSso: false,
    useKeyConnector: false,
    useScim: false,
    useGroups: false,
    useDirectory: false,
    useEvents: false,
    useTotp: true,
    use2fa: true,
    useApi: true,
    useSecretsManager: false,
    useResetPassword: false,
    usersGetPremium: true,
    useCustomPermissions: true,
    selfHost: true,
    hasPublicAndPrivateKeys: Boolean(org.public_key && org.private_key),
    usePasswordManager: true,
    smSeats: null,
    smServiceAccounts: null,
    maxAutoscaleSmSeats: null,
    maxAutoscaleSmServiceAccounts: null,
    limitCollectionCreation: false,
    limitCollectionDeletion: true,
    limitItemDeletion: false,
    allowAdminAccessToAllCollectionItems: true,
    useRiskInsights: false,
    useOrganizationDomains: false,
    useAdminSponsoredFamilies: false,
    useAutomaticUserConfirmation: false,
    useDisableSmAdsForUsers: true,
    usePhishingBlocker: false,
    useMyItems: false,
    useInviteLinks: false,
    usePam: false,
    object: "organization",
  };
}
