export {
	TotpSetupSchema,
	TotpVerifySchema,
	DisableTotpSchema,
	RecoverTwoFactorSchema,
	YubicoSettingsSchema,
	SaveYubicoKeysSchema,
	SaveYubicoConfigSchema,
	type TotpSetupInput,
	type TotpVerifyInput,
	type DisableTotpInput,
	type RecoverTwoFactorInput,
	type YubicoSettingsInput,
	type SaveYubicoKeysInput,
	type SaveYubicoConfigInput,
} from "@edgewarden/shared";
