import type { D1Dialect } from "@sundoge/kysely-d1";
import type { Kysely, Selectable } from "kysely";
import type { InferOutput } from "valibot";
import type { TokenFormSchema } from "./schemas/identity";
import type {
	AuthRequests,
	Ciphers,
	DB,
	Devices,
	Folders,
	OrgMembers,
	Collections,
	Sends,
	Users,
	WebauthnCredentials,
} from "./types/db";
import type { JWTPayload } from "./utils/jwt";

// CloudflareBindings is auto-generated by `pnpm run cf-typegen` → worker-configuration.d.ts
// It is a global interface — no import needed.

export type Variables = {
	db: Kysely<DB>;
	dbDialect: D1Dialect;
	user: Selectable<Users>;
	payload: JWTPayload;
	folder: Selectable<Folders>;
	device: Selectable<Devices>;
	authRequest: Selectable<AuthRequests>;
	cipher: Selectable<Ciphers>;
	send: Selectable<Sends>;
	sendFileId: string;
	tokenRequest: InferOutput<typeof TokenFormSchema>;
	revocationToken: string;
	accountPasskey: Selectable<WebauthnCredentials>;
	orgMember: Selectable<OrgMembers>;
	collection: Selectable<Collections>;
};

export type HonoEnv = {
	Bindings: CloudflareBindings;
	Variables: Variables;
};
